apiVersion: v1
kind: Pod
metadata:
  name: netcorek8s-liveness
spec:
  containers:
  - image: refactor2/netcorek8s:liveness
    name: netcorek8s
    livenessProbe:
      httpGet:
        path: /health
        port: 43300
    ports:
    - containerPort: 43300
      protocol: TCP