apiVersion: v1
kind: ReplicationController
metadata:
  name: netcorek8src
spec:
  replicas: 3
  selector:
    app: netcorek8s
  template:
    metadata:
      labels:
        app: netcorek8s
    spec:
      containers:
      - name: netcorek8s
        image: refactor2/netcorek8s:1.0
        ports:
        - containerPort: 43300