apiVersion: v1
kind: Service
metadata:
  name: netcorek8s-nodeport
spec:
  type: NodePort
  ports:
  - port: 13301
    targetPort: 43300
    nodePort: 32002
  selector:
    app: netcorek8spet