apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netcorek8s
spec:
  selector:
    matchLabels:
      app: netcorek8spet
  serviceName: netcorek8s-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: netcorek8spet
    spec:
      containers:
      - name: netcorek8s
        image: refactor2/netcorek8s:statefulset
        ports:
        - name: http
          containerPort: 43300
        volumeMounts:
        - name: data
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Mi
      accessModes:
      - ReadWriteOnce