apiVersion: v1
kind: Pod
metadata:
  name: curl-with-proxy
spec:
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: refactor2/kubectl-proxy:1.10.0